In [1]:
import mlflow
import pandas as pd
import mlflow.sklearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd
import re
import string
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import numpy as np

/home/harsh/mlflow-intro/mlops-mini-project/myenv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [29]:
# Data Imports

df = pd.read_csv('https://raw.githubusercontent.com/campusx-official/jupyter-masterclass/main/tweet_emotions.csv').drop(columns=['tweet_id'])
df.head()

    sentiment                                            content
0       empty  @tiffanylue i know  i was listenin to bad habi...
1     sadness  Layin n bed with a headache  ughhhh...waitin o...
2     sadness                Funeral ceremony...gloomy friday...
3  enthusiasm               wants to hang out with friends SOON!
4     neutral  @dannycastillo We want to trade with someone w...

In [30]:
# reducing dataset for faster processing. 

df = df[df['sentiment'].isin(['happiness', 'sadness'])]
df

       sentiment                                            content
1        sadness  Layin n bed with a headache  ughhhh...waitin o...
2        sadness                Funeral ceremony...gloomy friday...
6        sadness  I should be sleep, but im not! thinking about ...
8        sadness            @charviray Charlene my love. I miss you
9        sadness         @kelcouch I'm sorry  at least it's Friday?
...          ...                                                ...
39986  happiness  going to watch boy in the striped pj's hope i ...
39987  happiness  gave the bikes a thorough wash, degrease it an...
39988  happiness  had SUCH and AMAZING time last night, McFly we...
39994  happiness                      Succesfully following Tayla!!
39998  happiness  @niariley WASSUP BEAUTIFUL!!! FOLLOW ME!!  PEE...

[10374 rows x 2 columns]

In [31]:
# data preprocessing

# Define text preprocessing functions
def lemmatization(text):
    """Lemmatize the text."""
    lemmatizer = WordNetLemmatizer()
    text = text.split()
    text = [lemmatizer.lemmatize(word) for word in text]
    return " ".join(text)

def remove_stop_words(text):
    """Remove stop words from the text."""
    stop_words = set(stopwords.words("english"))
    text = [word for word in str(text).split() if word not in stop_words]
    return " ".join(text)

def removing_numbers(text):
    """Remove numbers from the text."""
    text = ''.join([char for char in text if not char.isdigit()])
    return text

def lower_case(text):
    """Convert text to lower case."""
    text = text.split()
    text = [word.lower() for word in text]
    return " ".join(text)

def removing_punctuations(text):
    """Remove punctuations from the text."""
    text = re.sub('[%s]' % re.escape(string.punctuation), ' ', text)
    text = text.replace('؛', "")
    text = re.sub('\s+', ' ', text).strip()
    return text

def removing_urls(text):
    """Remove URLs from the text."""
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

def normalize_text(df):
    """Normalize the text data."""
    try:
        df['content'] = df['content'].apply(lower_case)
        df['content'] = df['content'].apply(remove_stop_words)
        df['content'] = df['content'].apply(removing_numbers)
        df['content'] = df['content'].apply(removing_punctuations)
        df['content'] = df['content'].apply(removing_urls)
        df['content'] = df['content'].apply(lemmatization)
        return df
    except Exception as e:
        print(f'Error during text normalization: {e}')
        raise

In [32]:
df = normalize_text(df)
df.head()

  sentiment                                            content
1   sadness            layin n bed headache ughhhh waitin call
2   sadness                     funeral ceremony gloomy friday
6   sadness  sleep im not thinking old friend want married ...
8   sadness                       charviray charlene love miss
9   sadness                        kelcouch sorry least friday

In [33]:
df['sentiment'] = df['sentiment'].replace({'happiness':1, 'sadness':0})
df

/tmp/ipykernel_21501/1819606554.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sentiment'] = df['sentiment'].replace({'happiness':1, 'sadness':0})

       sentiment                                            content
1              0            layin n bed headache ughhhh waitin call
2              0                     funeral ceremony gloomy friday
6              0  sleep im not thinking old friend want married ...
8              0                       charviray charlene love miss
9              0                        kelcouch sorry least friday
...          ...                                                ...
39986          1              going watch boy striped pj s hope cry
39987          1  gave bike thorough wash degrease grease it thi...
39988          1           amazing time last night mcfly incredible
39994          1                        succesfully following tayla
39998          1  niariley wassup beautiful follow me peep new h...

[10374 rows x 2 columns]

In [34]:
vectorizer = CountVectorizer(max_features=1000)
X = vectorizer.fit_transform(df['content'])
y = df['sentiment']

In [35]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
import dagshub
dagshub.init(repo_owner='HarshVerma1233', repo_name='MLOps-Mini-Project', mlflow=True)

mlflow.set_tracking_uri('https://dagshub.com/HarshVerma1233/MLOps-Mini-Project.mlflow')

mlflow.set_experiment("Logistic Regression Baseline")

Accessing as HarshVerma1233

Initialized MLflow to track repo "HarshVerma1233/MLOps-Mini-Project"

Repository HarshVerma1233/MLOps-Mini-Project initialized!

Initialized MLflow to track repo "campusx-official/mlops-mini-project"

Repository campusx-official/mlops-mini-project initialized!

<Experiment: artifact_location='mlflow-artifacts:/c435ff68a68e430eb20e0be995600f51', creation_time=1722007422645, effective_trace_archival_retention=None, experiment_id='0', last_update_time=1722007422645, lifecycle_stage='active', name='Logistic Regression Baseline', tags={}, trace_location=None, workspace='default'>